version: '3.8'
services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ..:/workspace:cached
            - ~/.gitconfig:/home/developer/.gitconfig:ro
            - ~/.ssh:/home/developer/.ssh:ro
        command: sleep infinity